### ISSUE TITLE
短信登录发送短信后报错

### ISSUE THREAD

**Issue by auqhjjqdo** [lkeme/BiliHelper-personal#224]
报错如图
![image](https://github.com/lkeme/BiliHelper-personal/assets/84632728/aa901732-1112-4193-ac16-25faa1b73065)
实际短信是发送成功的，但是不能输入短信验证码，在极验的网页提交后就报这个错
环境是debian12 + docker，使用docker compose运行
```
version: '3'
services:
  BiliHelper-personal:
    image: lkeme/bilihelper-personal
    container_name: BiliHelper-personal
    environment:
      MIRRORS: 8
      CAPTCHA: 1
    volumes:
      - /opt/BiliHelper-personal/profile/user:/app/profile/user
    ports:
      - 50001:50001
    restart: on-failure:5
```

**Comment by lkeme** [comment]
```
配置文件里设置好，发送完短信 
docker attach 或者docker exec 再进去容器里输入
```

**Comment by auqhjjqdo** [comment]
> ```
> 配置文件里设置好，发送完短信 
> docker attach 或者docker exec 再进去容器里输入
> ```

我没有用-d参数后台运行，直接就在终端内前台运行也是输入不了验证码，报错后过几秒就停止运行了

**Comment by lkeme** [comment]
因为默认命令使用的是 `-itd`

所以`docker-compose`需要终端交互

```
version: '3'
services:
  BiliHelper-personal:
    image: lkeme/bilihelper-personal
    stdin_open: true
    tty: true
    ......

```
